version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bundle exec rails s --binding=0.0.0.0
  db:
    image: mysql
    volumes:
     - /Data/sql:/var/lib/mysql
     - ./docker/mysql/confs:/etc/mysql/conf.d
    environment:
     - MYSQL_ROOT_PASSWORD=pass
     - character-set-server=utf8mb4
     - collation-server=utf8mb4_unicode_ci
